modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="memeconomy"
version="2.0.1"
displayName="memeconomy"
displayURL="https://www.memefarmerstudios.com"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="meme farmer hamish"
description="the greatest economy of all time"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.memeconomy]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.memeconomy]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration