modLoader="javafml"
loaderVersion="[1.21,1.22)"
license="MIT"

[[mods]]
modId="memecoins"
version="1.0.0"

displayName="MemeCoins Mod"
authors="Your Name"
description="A simple mod that adds a custom coin item."

[[dependencies.memecoins]]
modId="neoforge"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
sided="BOTH"